using Shortener.ServiceDefaults;
using Shortener.Application;
using Shortener.Infrastructure;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Identity;

var builder = WebApplication.CreateBuilder(args);
builder.AddFoundation("shortener-api");
var app = builder.Build();

app.UseFoundation();
app.MapGet("/api/v1/auth/csrf", (IAntiforgery antiforgery, HttpContext http) => Results.Ok(new { requestToken = antiforgery.GetAndStoreTokens(http).RequestToken }));
app.MapPost("/api/v1/auth/register", async (RegisterInput input, AuthService auth, IEmailSender email, CancellationToken ct) => { if (input.Password.Length is < 12 or > 128) return Results.BadRequest(new { code = "invalid_input" }); var created = await auth.CreateUserAsync(input, ct); if (created is { } c) await email.SendAsync(c.User.Email!, "Confirme seu e-mail", $"POST /api/v1/auth/verify-email token={c.Token}", ct); return Results.Accepted(value: new { message = "Se os dados forem válidos, enviaremos instruções." }); });
app.MapPost("/api/v1/auth/verify-email", async (ActionTokenInput input, AuthService auth, CancellationToken ct) => await auth.ConsumeActionAsync(input.Token, "verify_email", null, ct) ? Results.NoContent() : Results.BadRequest(new { code = "invalid_token" }));
app.MapPost("/api/v1/auth/resend-verification", async (EmailInput input, AuthService auth, IEmailSender email, CancellationToken ct) => { var user = await auth.FindUserAsync(input.Email, ct); if (user is not null) { var entity = await auth.FindUserEntityAsync(input.Email, ct); if (entity is not null && entity.EmailVerifiedAt is null) await email.SendAsync(entity.Email!, "Confirme seu e-mail", "Use o token recebido para confirmar.", ct); } return Results.Accepted(value: new { message = "Se os dados forem válidos, enviaremos instruções." }); });
app.MapPost("/api/v1/auth/login", async (LoginInput input, AuthService auth, JwtIssuer issuer, HttpResponse response, CancellationToken ct) => { var result = await auth.LoginAsync(input, ct); if (result is null) return Results.Unauthorized(); var jwt = issuer.Issue(result.Value.Session, result.Value.User); response.Cookies.Append("__Secure-refresh", result.Value.Refresh, new CookieOptions { HttpOnly = true, Secure = true, SameSite = SameSiteMode.Strict, Path = "/api/v1/auth", Expires = result.Value.Session.ExpiresAt }); return Results.Ok(jwt); });
app.MapPost("/api/v1/auth/forgot-password", async (EmailInput input, AuthService auth, IEmailSender email, CancellationToken ct) => { var entity = await auth.FindUserEntityAsync(input.Email, ct); if (entity is not null) { var token = await auth.CreateActionToken(entity, "reset_password", TimeSpan.FromMinutes(30), ct); await email.SendAsync(entity.Email!, "Redefinição de senha", $"POST /api/v1/auth/reset-password token={token}", ct); } return Results.Accepted(value: new { message = "Se os dados forem válidos, enviaremos instruções." }); });
app.MapPost("/api/v1/auth/reset-password", async (ResetPasswordInput input, AuthService auth, CancellationToken ct) => input.NewPassword.Length is >= 12 and <= 128 && await auth.ConsumeActionAsync(input.Token, "reset_password", input.NewPassword, ct) ? Results.NoContent() : Results.BadRequest(new { code = "invalid_token" }));
app.MapPost("/api/v1/auth/refresh", async (HttpRequest request, AuthService auth, JwtIssuer issuer, HttpResponse response, CancellationToken ct) => { if (!request.Cookies.TryGetValue("__Secure-refresh", out var raw)) return Results.Unauthorized(); var result = await auth.RefreshAsync(raw, ct); if (result is null) return Results.Unauthorized(); var jwt = issuer.Issue(result.Value.Session, result.Value.User); response.Cookies.Append("__Secure-refresh", result.Value.Refresh, new CookieOptions { HttpOnly = true, Secure = true, SameSite = SameSiteMode.Strict, Path = "/api/v1/auth", Expires = result.Value.Session.ExpiresAt }); return Results.Ok(jwt); });
app.MapPost("/api/v1/auth/logout", async (HttpRequest request, AuthService auth, HttpResponse response, CancellationToken ct) => { if (request.Cookies.TryGetValue("__Secure-refresh", out var raw)) await auth.LogoutAsync(raw, ct); response.Cookies.Delete("__Secure-refresh", new CookieOptions { HttpOnly = true, Secure = true, SameSite = SameSiteMode.Strict, Path = "/api/v1/auth" }); return Results.NoContent(); });
app.MapGet("/api/v1/me", async (HttpContext http, AuthService auth, CancellationToken ct) => Guid.TryParse(http.User.FindFirst("sub")?.Value, out var id) && Guid.TryParse(http.User.FindFirst("sid")?.Value, out var sid) && await auth.GetUserAsync(id, sid, ct) is { } u ? Results.Ok(u) : Results.Unauthorized()).RequireAuthorization();
app.Run();
public partial class Program;
