using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Shortener.Infrastructure;

[DbContext(typeof(AppDbContext))]
[Migration("202609070002_AuthenticationHardening")]
public sealed class AuthenticationHardeningMigration : Migration
{
    protected override void Up(MigrationBuilder m) => m.Sql("""
        CREATE UNIQUE INDEX IF NOT EXISTS ix_users_normalized_user_name ON users(normalized_user_name);
        CREATE TABLE roles (id uuid PRIMARY KEY, name text, normalized_name text UNIQUE, concurrency_stamp text);
        CREATE TABLE user_roles (user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id uuid REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id, role_id));
        CREATE TABLE user_claims (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, claim_type text, claim_value text);
        CREATE TABLE role_claims (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE, claim_type text, claim_value text);
        CREATE TABLE user_logins (login_provider text, provider_key text, provider_display_name text, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(login_provider, provider_key));
        CREATE TABLE user_tokens (user_id uuid REFERENCES users(id) ON DELETE CASCADE, login_provider text, name text, value text, PRIMARY KEY(user_id, login_provider, name));
        CREATE TABLE auth_rate_limits (key text PRIMARY KEY, count integer NOT NULL, expires_at timestamptz NOT NULL);
        CREATE INDEX ix_auth_rate_limits_expires_at ON auth_rate_limits(expires_at);
        """);

    protected override void Down(MigrationBuilder m) => m.Sql("""
        DROP TABLE auth_rate_limits, user_tokens, user_logins, role_claims, user_claims, user_roles, roles;
        DROP INDEX ix_users_normalized_user_name;
        """);
}
